---

name: CI

on: [ push, pull_request ]

env:
  PY_COLORS: 1

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: ModelSim run
        run: |
          git submodule update --init --recursive
          docker pull suoto/dvb_fpga_ci
          docker/run_tests.sh --num-threads 4
